services:
  postgres:
    image: postgres:17
    container_name: realm-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: realm
      POSTGRES_PASSWORD: realm_password
      POSTGRES_DB: realm

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: